# Copyright 2023-2024 Alexander Stärk
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: NetCommonBuild

permissions:
  contents: write
  packages: write

on:
  workflow_call:
    inputs:
      basBuildType:
        description: 'The type of build that should be started. Supported values are ''Alpha'', ''CI'', ''Preview'', ''RC'' and ''Release''.'
        default: 'Preview'
        required: true
        type: string
      projectOrSolution:
        description: 'The project or solution that will be built. The default builds all solutions in the "src" directory of the repository.'
        default: 'src/*.sln'
        required: false
        type: string
      dotNetVersion:
        description: 'The version of .Net that will be used for the build.'
        default: 9.0.x
        required: false
        type: string
      publishTargetFramework:
        description: 'The target framework that will be used for publishing.'
        default: ''
        required: false
        type: string
      runsOn:
        description: 'Defines the type of machine to run the job on.'
        default: ubuntu-latest
        required: false
        type: string
      sonarProjectKey:
        description: 'The project key of the sonar project'
        default: ''
        required: false
        type: string
      sonarOrganization:
        description: 'The name of the sonar organization'
        default: ''
        required: false
        type: string
jobs:
  build:

    runs-on: ${{ inputs.runsOn }}

    steps:
    - name: Print Input Parameters
      run: |
        echo basBuildType = ${{ inputs.basBuildType }}
        echo projectOrSolution = ${{ inputs.projectOrSolution }}
        echo dotNetVersion = ${{ inputs.dotNetVersion }}
        echo publishTargetFramework = ${{ inputs.publishTargetFramework }}
        echo runsOn = ${{ inputs.runsOn }}
        echo sonarProjectKey = ${{ inputs.sonarProjectKey }}
        echo sonarOrganization = ${{ inputs.sonarOrganization }}
    
    - name: Validate Input Parameters
      if: inputs.basBuildType != 'Alpha' && inputs.basBuildType != 'CI' && inputs.basBuildType != 'Preview' && inputs.basBuildType != 'RC' && inputs.basBuildType != 'Release'
      run: |
        echo 'Please check the basBuildType input. Supported values are ''Alpha'', ''CI'', ''Preview'', ''RC'' and ''Release''.'
        exit 1
    
    - name: Set up JDK 17 # necessary for Sonar
      uses: actions/setup-java@v4
      if: inputs.sonarProjectKey != '' && inputs.sonarOrganization != ''
      with:
        java-version: 17
        distribution: 'zulu' # Alternative distribution options are available.
    
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Shallow clones should be disabled for versioning and a better relevancy of sonar analysis
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotNetVersion }}
        dotnet-quality: 'ga'
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v4
      if: inputs.sonarProjectKey != '' && inputs.sonarOrganization != ''
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      if: inputs.sonarProjectKey != '' && inputs.sonarOrganization != ''
      with:
        path: .\.sonar\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner
    
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true' && inputs.sonarProjectKey != '' && inputs.sonarOrganization != ''
      run: |
        mkdir -p .sonar/scanner
        dotnet tool update dotnet-sonarscanner --tool-path .sonar/scanner
    
    - name: Git Semantic Versioning
      id: versioning
      uses: PaulHatch/semantic-version@v5.4.0
      with:
        branch: ${{ github.ref_name }} # default is HEAD
        major_pattern: "BREAKING CHANGE:" # default is (MAJOR)
        minor_pattern: "feat:" # default is (MINOR)
        version_format: "${major}.${minor}.${patch}${{ inputs.basBuildType != 'Release' && format('-{0}${{increment}}', inputs.basBuildType) || '' }}"
        # If true, the body of commits will also be searched for major/minor patterns to determine the version type.
        #search_commit_body: # default is false
    
    - name: Compose padded version
      id: version_padded
      run: |
        MAJOR="${{ steps.versioning.outputs.major }}"
        MINOR="${{ steps.versioning.outputs.minor }}"
        PATCH="${{ steps.versioning.outputs.patch }}"
        INCREMENT="${{ steps.versioning.outputs.increment }}"
        LABEL="${{ inputs.basBuildType }}"
        
        if [[ "$LABEL" == "Release" ]]; then
          VERSION="$MAJOR.$MINOR.$PATCH"
        else
          PADDED=$(printf "%05d" "$INCREMENT")
          VERSION="$MAJOR.$MINOR.$PATCH-${LABEL}${PADDED}"
        fi
        
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
    
    - name: Dotnet Restore
      run: dotnet restore ${{ inputs.projectOrSolution }}
    
    - name: Start Sonar Analysis
      if: inputs.sonarProjectKey != '' && inputs.sonarOrganization != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          PR_PARAMS="/d:sonar.pullrequest.key=${{ github.event.pull_request.number }} /d:sonar.pullrequest.branch=${{ github.head_ref }} /d:sonar.pullrequest.base=${{ github.base_ref }} /d:sonar.github.repository=${{ github.repository }} /d:sonar.github.oauth=${{ secrets.GITHUB_TOKEN }}"
        else
          PR_PARAMS=""
        fi
        
        .sonar/scanner/dotnet-sonarscanner begin /k:"${{ inputs.sonarProjectKey }}" /o:"${{ inputs.sonarOrganization }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/TestResults/*/coverage.opencover.xml" $PR_PARAMS
    
    - name: Dotnet Build
      run: dotnet build ${{ inputs.projectOrSolution }} -c Release --no-restore -p:BAS_CB_VersionMajor=${{ steps.versioning.outputs.major }} -p:BAS_CB_VersionMinor=${{ steps.versioning.outputs.minor }} -p:BAS_CB_VersionBuild=${{ steps.versioning.outputs.patch }} -p:BAS_CB_VersionRevision=${{ steps.versioning.outputs.increment }} -p:BAS_CB_BuildType=${{ inputs.basBuildType }}
        
    - name: Dotnet Test
      run: dotnet test ${{ inputs.projectOrSolution }} -c Release --no-build --verbosity normal --collect:"XPlat Code Coverage" -p:BAS_CB_VersionMajor=${{ steps.versioning.outputs.major }} -p:BAS_CB_VersionMinor=${{ steps.versioning.outputs.minor }} -p:BAS_CB_VersionBuild=${{ steps.versioning.outputs.patch }} -p:BAS_CB_VersionRevision=${{ steps.versioning.outputs.increment }} -p:BAS_CB_BuildType=${{ inputs.basBuildType }}
    
    - name: End Sonar Analysis
      if: inputs.sonarProjectKey != '' && inputs.sonarOrganization != ''
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        .sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
    
    - name: Dotnet Publish
      run: dotnet publish ${{ inputs.projectOrSolution }} -c Release --no-build ${{ inputs.publishTargetFramework != '' && format('-f {0}', inputs.publishTargetFramework) || '' }} -p:BAS_CB_VersionMajor=${{ steps.versioning.outputs.major }} -p:BAS_CB_VersionMinor=${{ steps.versioning.outputs.minor }} -p:BAS_CB_VersionBuild=${{ steps.versioning.outputs.patch }} -p:BAS_CB_VersionRevision=${{ steps.versioning.outputs.increment }} -p:BAS_CB_BuildType=${{ inputs.basBuildType }}
    
    - name: Attach Build Artifacts to Workflow Run
      uses: actions/upload-artifact@v4.3.3
      with:
        name: Artifacts
        path: src/artifacts/publish/**
        if-no-files-found: error
        retention-days: 10
    
    - name: Dotnet Pack
      run: dotnet pack ${{ inputs.projectOrSolution }} -c Release -p:BAS_CB_VersionMajor=${{ steps.versioning.outputs.major }} -p:BAS_CB_VersionMinor=${{ steps.versioning.outputs.minor }} -p:BAS_CB_VersionBuild=${{ steps.versioning.outputs.patch }} -p:BAS_CB_VersionRevision=${{ steps.versioning.outputs.increment }} -p:BAS_CB_BuildType=${{ inputs.basBuildType }}
    
    - name: Attach NuGet Artifacts to Workflow Run
      uses: actions/upload-artifact@v4.3.3
      with:
        name: NuGet Packages
        path: src/artifacts/package/**/*.nupkg
        if-no-files-found: error
        retention-days: 10
    
    - name: Create Git Tag
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/v${{ steps.version_padded.outputs.version }}',
            sha: context.sha
          })
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: inputs.basBuildType == 'Release' || inputs.basBuildType == 'RC' || inputs.basBuildType == 'Preview'
      with:
        files: src/**/*.nupkg
        tag_name: v${{ steps.version_padded.outputs.version }}
        prerelease: ${{ inputs.basBuildType != 'Release' }}
    
    - name: Dotnet NuGet Push NuGet.org
      if: inputs.basBuildType == 'Release' || inputs.basBuildType == 'RC' || inputs.basBuildType == 'Preview'
      run: dotnet nuget push src/**/*.nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
      
    - name: Dotnet NuGet Push GitHub
      run: dotnet nuget push src/**/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{ secrets.GITHUB_TOKEN }}
